In [ ]:
CODING FROM SCRATCH

In [13]:
import numpy as np

# SMALL SAMPLE TEST FOR TRAINING

In [14]:
# generate 100 random values for 5 variables
a = np.random.rand(100)
b = np.random.rand(100)
c = np.random.rand(100)
d = np.random.rand(100)
e = np.random.rand(100)

y = a**2 + b**2 + c**2 + d**2 + e**2

data = np.column_stack((a, b, c, d, e, y))
print(data[:5])

[[0.92302664 0.26027918 0.0162809  0.35818125 0.3504784  1.17111741]
 [0.71405224 0.61965242 0.75200409 0.70896379 0.79751147 2.59800407]
 [0.36761815 0.43729649 0.82487578 0.23113904 0.91053896 1.88929784]
 [0.93613488 0.50552176 0.92425423 0.13760418 0.05741245 2.00837774]
 [0.87792125 0.56452723 0.14664381 0.10291861 0.53135172 1.40386802]]


## Code and Logic Outline

In [101]:
#feed forward phase
'''
Okay
'''
def activation_fn(x):
    return 1 / (1 + np.exp(-x))
def activation_derivative(x):
    return activation_fn(x) * (1 - activation_fn(x))

alpha = 0.1
w_ih = np.random.rand(5, 7) # weight matrix from input layer to hidden layer
res1 = np.random.rand(7)
w_ho = np.random.rand(7, 1) # weight matrix from hidden layer to output layer
res2 = np.random.rand(1)
b_ih = np.random.rand(7) # bias for hidden layer 
b_ho = np.random.rand(1) # bias for output layer

for k, rw in enumerate(data[:, :5]):
    #beginning of the feed forward phase
    print(res1.shape)
    print(rw.T.shape)
    print(w_ih[:, ].shape)
    
    #step 1 - from i/p layer to hidden layer
    for i in range(len(w_ih[0])):
        res1[i] = np.dot(rw.T, w_ih[:, i]) + b_ih[i]
    print(res1)
    act_arr1 = activation_fn(res1)
    #step 2 - from hidden layer to output layer
    for i in range(len(w_ho[0])):
        res2[i] = np.dot(act_arr1,w_ho[:,i]) + b_ho[i]
    act_arr2 = activation_fn(res2)
    print(res2)


    #backpropagation begins
    print("___________________________________________")
    #output to hidden layer
    del_k = (data[k, -1]-act_arr2)*activation_derivative(res2)
    del_k = del_k.reshape(-1, 1)
    del_w_ho = alpha * np.outer(del_k, act_arr1)
    del_b_ho = alpha*del_k
   
    #hidden to input layer
    #del_in_h
    del_in_j = w_ho @ del_k 
    print(del_in_j)   # 7x1 array column array
    print(del_in_j.shape)  # Check shape of del_in_j
    del_j = del_in_j*(activation_derivative(res1).reshape(-1, 1))
    print(del_j.shape)  

    del_w_ih = alpha*(del_j*rw)
    del_b_ih = alpha*del_j
    print(del_w_ih.shape)
    print("Hello")

    #updating the weights
    w_ho = w_ho + del_w_ho
    w_ih = w_ih + del_w_ih.T
    b_ho = b_ho + del_b_ho
    b_ih = b_ih + del_b_ih
    print(w_ho.shape)
    print(w_ih.shape)
    print(b_ho.shape)
    print(b_ih.shape)
    print("___________________________________________")
    break
    

(7,)
(5,)
(5, 7)
[1.58417326 2.31891553 1.62539946 0.92992755 2.05295214 1.76058845
 0.8706455 ]
[2.89130208]
___________________________________________
[[0.00290044]
 [0.00249088]
 [0.0005824 ]
 [0.00651812]
 [0.00624076]
 [0.00189901]
 [0.00779762]]
(7, 1)
(7, 1)
(7, 5)
Hello
(7, 7)
(5, 7)
(1, 1)
(7, 7)
___________________________________________


#  BACKPROPAGATED FEEDFORWARD NEURAL NETWORK

In [126]:


def activation_fn(x):
    return 1 / (1 + np.exp(-x))

def activation_derivative(x):
    return activation_fn(x) * (1 - activation_fn(x))

alpha = 0.1
w_ih = np.random.rand(5, 7)  # weight matrix from input layer to hidden layer
res1 = np.random.rand(1, 7)  # Initialize res1 as a row vector
w_ho = np.random.rand(7, 1)  # weight matrix from hidden layer to output layer
res2 = np.random.rand(1, 1)  # Initialize res2 as a scalar
b_ih = np.random.rand(1, 7)  # bias for hidden layer
b_ho = np.random.rand(1, 1)  # bias for output layer

for k, rw in enumerate(data[:, :5]):
    rw = np.atleast_2d(rw)
    
    # Beginning of the feed forward phase
    print(res1.shape)
    print(rw.shape)
    print(w_ih.shape)
    
    # Step 1 - from input layer to hidden layer
    res1 = np.dot(rw, w_ih[:, i]) + b_ih
    print(res1)
    act_arr1 = activation_fn(res1)
    
    # Step 2 - from hidden layer to output layer
    res2 = np.dot(act_arr1, w_ho) + b_ho
    print(res2)
    act_arr2 = activation_fn(res2)

    # Backpropagation begins
    print("___________________________________________")
    # Output to hidden layer
    del_k = (data[k, -1] - act_arr2) * activation_derivative(res2)
    del_w_ho = alpha * np.dot(act_arr1.T, del_k)
    del_b_ho = alpha * np.sum(del_k)
    
    # Hidden to input layer
    del_in_j = np.dot(del_k, w_ho.T)
    del_j = del_in_j * activation_derivative(res1)
    del_w_ih = alpha * np.dot(rw.T, del_j)
    del_b_ih = alpha * np.sum(del_j)
    print(del_w_ih.shape)
    print(del_w_ho.shape)

    # Updating the weights
    w_ho += del_w_ho
    w_ih += del_w_ih
    b_ho += del_b_ho
    b_ih += del_b_ih
    print("___________________________________________")



(1, 7)
(1, 5)
(5, 7)
[[2.12602058 1.57116211 2.10326499 1.36761946 1.92948479 1.7764791
  1.4349576 ]]
[[3.45073553]]
___________________________________________
(5, 7)
(7, 1)
___________________________________________
(1, 7)
(1, 5)
(5, 7)
[[3.10862504 2.55376657 3.08586945 2.35022392 2.91208925 2.75908356
  2.41756206]]
[[3.752495]]
___________________________________________
(5, 7)
(7, 1)
___________________________________________
(1, 7)
(1, 5)
(5, 7)
[[2.51439183 1.95953336 2.49163623 1.75599071 2.31785604 2.16485035
  1.82332885]]
[[3.62415587]]
___________________________________________
(5, 7)
(7, 1)
___________________________________________
(1, 7)
(1, 5)
(5, 7)
[[2.1582718  1.60341332 2.1355162  1.39987068 1.96173601 1.80873031
  1.46720882]]
[[3.5066057]]
___________________________________________
(5, 7)
(7, 1)
___________________________________________
(1, 7)
(1, 5)
(5, 7)
[[2.2808717  1.72601322 2.2581161  1.52247058 2.08433591 1.93133021
  1.58980872]]
[[3.5743133]]
__