In [13]:
import numpy as np

In [14]:
# generate 100 random values for 5 variables
a = np.random.rand(100)
b = np.random.rand(100)
c = np.random.rand(100)
d = np.random.rand(100)
e = np.random.rand(100)

y = a**2 + b**2 + c**2 + d**2 + e**2

data = np.column_stack((a, b, c, d, e, y))
print(data[:5])

[[0.92302664 0.26027918 0.0162809  0.35818125 0.3504784  1.17111741]
 [0.71405224 0.61965242 0.75200409 0.70896379 0.79751147 2.59800407]
 [0.36761815 0.43729649 0.82487578 0.23113904 0.91053896 1.88929784]
 [0.93613488 0.50552176 0.92425423 0.13760418 0.05741245 2.00837774]
 [0.87792125 0.56452723 0.14664381 0.10291861 0.53135172 1.40386802]]


In [23]:
#feed forward phase
'''
Okay
'''
def activation_fn(x):
    return 1 / (1 + np.exp(-x))
def activation_derivative(x):
    return activation_fn(x) * (1 - activation_fn(x))

w_ih = np.random.rand(5, 7) # weight matrix from input layer to hidden layer
res1 = np.random.rand(7)
w_ho = np.random.rand(7, 1) # weight matrix from hidden layer to output layer
res2 = np.random.rand(1)
b_ih = np.random.rand(7) # bias for hidden layer 
b_ho = np.random.rand(1) # bias for output layer

for k, rw in enumerate(data[:, :5]):
    #beginning of the feed forward phase
    
    #step 1 - from i/p layer to hidden layer
    for i in range(len(w_ih[0])):
        res1[i] = np.dot(rw, w_ih[:, i]) +  b_ih[i]
    print(res1)
    act_arr1 = activation_fn(res1)
    #step 2 - from hidden layer to output layer
    for i in range(len(w_ho[0])):
        res2[i] = np.dot(act_arr1,w_ho[:,i]) + b_ho[i]
    print(res2)
    act_arr2 = activation_fn(res2)


    #backpropagation begins
    
    

[1.94264693 1.92074498 0.96442915 1.06815932 0.91763526 1.32563409
 1.47413088]
[2.47401254]
[2.95600082 3.14933093 1.77247536 1.99997639 1.27278843 1.74899951
 2.14506655]
[2.68493324]
[2.51341735 2.43389506 1.43405001 1.69013832 1.24233516 1.24428976
 1.53884426]
[2.62156395]
[2.24290745 2.34156329 0.92465105 1.5689231  1.18826518 1.48743088
 1.52815495]
[2.57457396]
[2.03226711 2.08558011 1.14248852 1.33773547 0.99868589 1.61456871
 1.57243203]
[2.52528246]
[1.56042027 1.4728353  0.91134158 1.16981796 0.80238957 0.6182863
 1.19969637]
[2.40556551]
[2.19820142 2.41461179 1.21960231 1.68586066 1.04753631 1.55985284
 1.78940096]
[2.57426542]
[2.19297062 2.01348914 1.07776381 1.36459772 1.14339315 0.92126609
 1.25404742]
[2.54572428]
[2.34916284 2.63878634 1.17456999 1.90287894 1.18373892 1.7433753
 1.83393511]
[2.61567803]
[2.03987031 1.93090666 1.28189586 1.24155442 0.94597772 1.10529254
 1.45365502]
[2.50896805]
[2.90400682 3.08037229 1.87927095 2.00500091 1.18870578 1.47381078
 2.16

In [16]:



new_array = np.copy(data[:5])
new_array = new_array[:, :5]
print(new_array)
for rw in new_array:
    #step 1 - from i/p layer to hidden layer
    for i in range(len(w_ih[0])):
        res1[i] = np.dot(rw, w_ih[:, i]) +  b_ih[i]
    print(res1)
    act_arr1 = activation_fn(res1)

    #step 2 - from hidden layer to output layer
    for i in range(len(w_ho[0])):
        res2[i] = np.dot(act_arr1,w_ho[:,i]) + b_ho[i]
    print(res2)
    act_arr2 = activation_fn(res2)
    



[[0.92302664 0.26027918 0.0162809  0.35818125 0.3504784 ]
 [0.71405224 0.61965242 0.75200409 0.70896379 0.79751147]
 [0.36761815 0.43729649 0.82487578 0.23113904 0.91053896]
 [0.93613488 0.50552176 0.92425423 0.13760418 0.05741245]
 [0.87792125 0.56452723 0.14664381 0.10291861 0.53135172]]
[1.44375284 1.28837497 1.32154293 1.08378485 1.73349453 1.64052438
 1.47523708]
[3.02211138]
[1.9682529  1.96225541 2.09493159 1.95928214 2.27705477 2.25156181
 1.68759467]
[3.23933967]
[1.68895579 1.81340112 1.73073722 1.54298435 1.62581008 1.8290078
 1.05283892]
[3.1114728]
[1.59746691 1.67909309 1.82032839 0.80124842 2.05358896 1.60239818
 1.48187623]
[3.07934571]
[1.74529305 1.39977275 1.3621996  1.13320535 1.65431473 1.63090302
 1.3484517 ]
[3.06069671]
